alias: null
batch_size: 4
d_ff: 4
d_layers: 1
drop_last_loader: false
dropout: 0.1
e_layers: 2
early_stop_patience_steps: 0
factor: 1
futr_exog_list: null
h: 1
hidden_size: 128
hist_exog_list: null
input_size: 4
learning_rate: 0.001
loss: !!python/object:__main__.CustomBCELoss {}
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 1000
n_heads: 2
n_series: 1080
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: identity
stat_exog_list: null
step_size: 1
use_norm: true
val_check_steps: 100
valid_loss: !!python/object:__main__.CustomBCELoss {}
